---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    app: rabbitmq
    role: web
spec:
  type: LoadBalancer
  ports:
  - port: 15672
    name: management
  selector:
    app: rabbitmq
